#CLIENT_ID = "ngumBHLaPfWOZxYfqCs0pFgq41Os4BZs"
ENV['SOUNDCLOUD_CLIENT_ID'] = "ngumBHLaPfWOZxYfqCs0pFgq41Os4BZs"
ENV['SOUNDCLOUD_CLIENT_ID2'] = "Urn1Qv5ycnkT1uxyHcm61LR1ZNOvuUs9"
ENV['SESSION_PASSWORD'] = "password"
